#!/usr/bin/env python3
"""Loudness-match factory presets.
Runs `KeysKillaTests -cal` (renders every preset) and writes Source/PresetGains.h with the output gain
that brings each preset to the target short-term loudness. Run twice after big preset changes."""
import subprocess, sys
exe, target = sys.argv[1], -15.0
out = subprocess.run([exe, "-cal"], capture_output=True, text=True).stdout
rows = []
for line in out.strip().splitlines():
    name, g, win = line.rsplit("|", 2)
    g, win = float(g), float(win)
    new = max(-24.0, min(12.0, round(g + (target - win), 1)))
    rows.append((name, new, win))
with open("Source/PresetGains.h", "w") as f:
    f.write("#pragma once\n// Generated by tests/calibrate.py - loudness-matched output gain per factory preset (dB).\n")
    f.write("struct PresetGain { const char* name; float gain; };\ninline const PresetGain presetGains[] {\n")
    for name, new, _ in rows:
        f.write('    { "%s", %.1ff },\n' % (name.replace('"', '\\"'), new))
    f.write("};\n")
wins = [w for _, _, w in rows]
print(f"{len(rows)} presets, short-term loudness before this pass: {min(wins):.1f} .. {max(wins):.1f} dB")
